services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: currency_converter_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - currency_converter_network

  currency_converter:
    image: currency_converter
    container_name: currency_converter
    build:
      context: ./app
    ports:
      - 8000:8000
    networks:
      - currency_converter_network
    depends_on:
      - db
    restart: always

networks:
  currency_converter_network:
    driver: bridge

volumes:
  pgdata: